name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: install
        run: npm i

      - name: lint js
        run: npm run lint:js -- --max-warnings=0

      - name: lint style
        if: always()
        run: npm run lint:style
