name: translations
on:
  push:
    branches:
      - 'experimental'
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:

jobs:
  update-translations:
    name: update translations
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: experimental
          token: ${{ secrets.VOCASCAN_BOT_TOKEN }}

      - name: download
        uses: localazy/download@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}

      - name: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[skip ci] updated translations via Localazy"
          commit_user_name: VocascanBot
          commit_user_email: vocascan@gmail.com
          commit_author: VocascanBot <vocascan@gmail.com>
          file_pattern: src/i18n/locales/**/*.json
          branch: experimental

      - name: get version
        id: prepare
        run: |
          mv package.json package.json.bak
          npm i --no-save --no-package-look semver
          mv package.json.bak package.json
          version=$(node -e "
            const Semver = require('semver');
            const package = require('./package.json');
            const semver = Semver.parse(package.version);
            let version = 0;
            if (semver) {
              version = 100000000 * semver.major + 10000 * semver.minor + semver.patch;
            }
            console.log(version.toString(10));
          ")
          echo ::set-output name=version::${version}

      - name: upload
        uses: localazy/upload@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
          app_version: ${{ steps.prepare.outputs.version }}
